### ISSUE TITLE
Markdown지원 → 완료 / RTF 인코딩 → 보류

### ISSUE THREAD

**Issue by hynchl** [hynchl/distribusi-foh#2]
ㅜㅜ

**Comment by hynchl** [comment]
그런데 markdown은 쉽게 지원이 될 것 같습니다.
마크다운에 들어간 글씨 두께 등 효과 등을 살려서 갈지 플레인 텍스트로 갈지에 대해서 논의 후에 적용해보면 좋을 것 같아요!

**Comment by hynchl** [comment]
구현 완료! 하지만 아직 merge는 안했습니다.

**Comment by applecargo** [comment]
merge 해도 좋지 않을까 싶기도 한데..
근데, 사실 md를 써서 좋은점이 뭘까요?

지금, md 때문에 vimeo 링크 붙여넣기 하면서 <, > 가 생성되는 바람에 오류가 나는 경우를 사람들이 겪고 있어서...
뭔가 서버쪽에서 md 를 끄면 좋을지도 싶기도 해요..

**Comment by hynchl** [comment]
cloud에서 바로 글을 작성할 수 있다는 점(저장할 때 확장자를 바꾸지 않고도) 때문에 md를 지원해야한다고 생각했어요.
