### ISSUE TITLE
디자인 적용 과정

### ISSUE THREAD

**Issue by hynchl** [hynchl/distribusi-foh#5]
디자인을 적용해보고 있습니다. 아래는 샘플 파일입니다.

https://frog2.dianaband.info/src/test/sample_home.html

**이미지 리소스와 스타일 시트등은 저희 서버에 올려두고 html 코드에서 가져옵니다.**
서버에서 텍스트 편집기로 스타일 시트를 수정하면 바로 반영되지만! 권장하지 않습니다.
그래서 저희 클라우드(2)에 src라는 폴더를 만들었습니다.
(현재 레포를 pull하고 로컬에서 테스트해도 바로 보실 수 있습니다.)

가운데 정렬된 환대의 조각 로고가 왼쪽의 메뉴와 겹쳐보이기 때문에
720px 이하가 되면 모바일 버전으로 넘어가도록 구현할 계획입니다.
브라우저 너비가 1680px 정도 이상이 되면 메뉴나 본문의 크기를 수정해줘야할것 같습니다.
(맥북 15인치에서 고해상도로 보면 엄청 광활해지기 때문에 그런 생각을 했습니다)
**=> 기준이 되는 픽셀 너비를 720, 1680 정도로 간단하게 가져가면 좋을 것 같습니다.
그러나 우선 1680이상인 경우는 고려하지 않고 720 미만, 이상인 2가지 경우만 고려해서
반응형 작업을 진행하겠습니다!
**

스타일 시트 작업을 시작했으니 각 페이지별로 이번주에 스타일 시트 작업을 어느정도 마무리하고,
디자이너님과 수정이 필요한 사항(글씨 크기 등)을 의논하고 반영하면 좋을 것 같고
이번주 미팅전까지 각 페이지별 대략적인 스타일 시트 작업을 마치고,
 SVG 조각들을 잘 포맷팅해서 메인과 작가 페이지에 올려놓는 작업을 하는게 목표입니다!

아래는 이번주 미팅 전까지 작업 할 순서입니다!

- [x] Menubar, Logo 얹기
- [x] ABOUT
- [x] FRAGMENTS (작가들 페이지)
- [x] 작가 개인 페이지
- [x] HOME -- 조각들 얹기 (새로 파일을 받고나서)

**Comment by hynchl** [comment]
그리고 distribusi 코드에 고맙게도 어떤 폴더의 index.html이 distribusi에 의해 생성된 것이 아니면
해당 폴더에서 작업하지 않도록 코드가 짜져 있는 것을 발견했습니다! 귀찮은 일이 줄었다는 기쁨...

**Comment by hynchl** [comment]
- [x] 모바일 대응(720px 이하)
- [x] SVG 포맷팅 ===> 물리 시뮬레이션 효율화를 위해서 단순한 polygon shape의 도형을 새로 그려 넣어줌
        - 행간은 나중에하고
        - 모바일에서 이슈가 되는 부분은 아카이브를 어떻게 할것인지(모바일은 호버가 없기 때문에)
        - 모바일에서는 푸터가 필요한 것 같기도?
        - 현재 적용된 내용들 괜찮은지?
- [x] `matter.js` simulation test(optional) --- 간단한 테스트만 완료한 상황!

https://frog2.dianaband.info/TEST/home.html

**Comment by hynchl** [comment]
작가 정보는 따로 데이터베이스를 만들어서 불러오는 게 좋을 것 같아요.(json이어도 좋구요).
`window.location`을 이용하면 현재 url을 알 수 있기 때문에 어떤 작가의 페이지에 있는지 알 수 있으니까요!
첫 페이지도 최신 조각들을 디스트리뷰시에서 렌더링을 해주기보다는 따로 데이터베이스(혹은 json)을 참조해서 렌더해주는게 좋지 않을까...하는 생각이 들었습니다.

**Comment by hynchl** [comment]
- [x] `feature/index` 리뷰
- [x] merge
- [x] 작가 소개 정리(아래와 같은 포맷으로)
```
    {
        "name":"김현철",
        "path":"Hyunchul_Kim/",
        "fragId":"hyunchulKim",
        "introduction":"인간-컴퓨터 상호작용을 공부하는 학생이고..."
    },
```

- [x] 코드 정리
- [x] SVG 포맷팅 확정 짓기 --- 사용하기 좋게!
- [x] SVG의 위치값과 캔버스 내의 위치값(body.position)의 비례? 관계 알아보기
      애니메이션 처음 시작할 때 모양들이 튕겨나가는 문제
- [x] `matter.js`로 svg 제어하기
       - 1.  충분히 떨어진 상태로 시작하도록
       - 2.  환대의 조각 로고나 어바웃 타임라인 아이콘 정보도 환경에 반영
       - 3.  애니메이션 퀄리티를 조정할 수 있는 파라메터를 떼어 놓고 코드 정리
       - 4.  스크롤에 따라서 새로 파일이 로드되는 로직 구현(피직스 상에서 어떻게 처리할 것인지도)
- [x] `matter.js`에서 transform rotation 구속하거나, 아니면 svg에서 회전도 가능하게 하기

**Comment by hynchl** [comment]
### 확인 요청할 부분
- 돌고래 : 작가 소개만 있음. 폴더와 조각 그림에 해당하는 것을 찾지 못함 ==> 현진 님
- 이두호, 송수연, 노들야학, 현진, 정진호, 홍서연 : 작가소개 찾지 못함 ==> http://never.gonetis.com:9002/p/0000fregments_of_hospitality
- pzzz: 조각그림에만 있으며 소개와 폴더 찾지 못함 ==> 0set
- 선언문을 열면 어떤 일이? ==> 패드로 연결

**Comment by hynchl** [comment]
**SVG** 
- [x] SVG 애니메이션을 통해서 움직이는 모습 확인(데스크탑)
- [ ] resize에 대응해주기(우선순위 낮음)
- [ ] 모바일 크기에 적절한 셋업 해주기(SVG가 가장 큰 값에 의해서 실시간으로 바뀌도록) -- 우선순위 높음

**작가페이지**
- [x] 페이지에 따라서 작가 정보 불러오기(급함) --- 작가 정보, 조각 정보(이게 무엇인지 확인 필요)
- [x] 디스트리뷰시에 적용하고 디자인 적용된 모습 공유 --- 화요일까지
- [x] 조각을 눌러서 접근했을 때 진입 효과(해쉬 이벤트!)

**메인 페이지**
- [x] 조각들 정렬해서 최신순 조각 부터 표시(진행중)
- [x] 스크롤하면 조각들이 밑부분에 계속 추가 되는 식으로

**프로젝트 소개**
- [x] 모바일에서는 왼쪽 정렬
- [x] 웹에서는 칼럼의 왼쪽 마진 오른쪽 마진 맞춰주기

**Comment by hynchl** [comment]
* 스타일 관련 이슈는 금요일 오후 작업 가능할 것 같음(미팅을 해야하기 때문에 메인 페이지보다 우선순위)
- [x] 조각을 눌러서 접근했을 때 진입 효과(해쉬 이벤트!)
- [ ] 모바일 크기에 적절한 셋업 해주기(SVG가 가장 큰 값에 의해서 실시간으로 바뀌도록) -- 우선순위 높음
* 저녁에 frog2에서 테스트 해보고 frog에 적용할 수 있길 바람...
* 메인 텍스트 조각들에 대한 부분이 제대로 되지 않을 수 있음

**Comment by hynchl** [comment]
** SVG 안에 a tag 안에 있는 g를 생성해서 넣었을 때 안보이는 문제 ** ==> 
- [x] ~시도해보자 → https://github.com/dnozay/innersvg-polyfill~
- [x] 위계 바꾸기
SVG 안에 HTML요소를 동적으로 넣을 때 렌더가 안되는 상황이 있는 것 같다.
그래서 <g> 안에 <a>를 넣어보았는데 작동해서(ㅜㅜ) 그대로 적용함

**Comment by hynchl** [comment]
세원 님에게 요청해야할 사항 --- 현재 최신 파일 pull 받아서 진행 부탁드립니다!
1. root folder(지금은 test_data)에서 index.html 만들지 않도록
2. test_data안에 `index.json`이 들어오도록(임시로 코드에 적어놓은 상태)

**Comment by hynchl** [comment]
### 디자인 관련해서 못한 부분😭
- [ ] 조각 위의 숫자
- [ ] resize에 대응

**Comment by hynchl** [comment]
### DONE
- [x] `<pre>` 태그 없애주기(글줄바꿈을 못함)
- [x] 조각 선택 시 무지개 효과 3초
- [x] 선언문/인스타그램,페이스북 새창에서 뜨도록 수정
- [x] 몇몇 조각의 숫자가 보이지 않고 참여자 이름이 보이는 문제 <== 태그 순서의 문제
- [x] 참여자 화면에서 보이는 조각의 크기를 전체 페이지에서 보이는 조각 크기와 같게.
 아래 코드를 통해서 `<img>`를 통해서 가져온 `svg`파일의 사이즈를 원본 사이즈로 바꿔줄 수 있음
```
width: fit-content;
```
- [x] 아카이브의 위치 조정 ← 왜 어렵지?
`z-index` 조정해서 해결!
- [x] 사파리-아이폰 아카이브 클로즈 안됨
모바일에서 호버 효과를 없애기
- [x] 사이드 스크롤이 필요한 경우
- [x] 스크롤 이동
https://stackoverflow.com/questions/49820013/javascript-scrollintoview-smooth-scroll-and-offset
**https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header**

### 기다렸다가 할 일
- [x] 디플로이 부탁드리고 아카이브 위치 조정하고 모바일 대응한 것, 작가 조각 모양 수정한 것 잘되는지 확인
- [x] 작가페이지도 메인 페이지처럼 얌전하게 나타나는게 좋지 않을까?
- [ ] 각 작가 페이지에서 로드 ← ??? 기억이 안나요 흑흑
- [ ] 조각들의 크기가 고르지 않은 것 같음
- [ ] about에 영문 번역 추가
- [ ] about에 일문 번역 추가


### for the next release
- [ ] 파폭 스크롤 로딩 문제; 파이어폭스에서 SVG추가 생성 불가 -- 지원 여부 확인 후 가능하다면 다음번에 진행
- [ ] dark mode
- [ ] 페이지 간 이동 시에 이전 페이지의 정보(스크롤 위치 로딩된 조각)을 그대로 둘 수 있을까? -- 탐색

**Comment by sewonist** [comment]
> 페이지 간 이동 시에 이전 페이지의 정보(스크롤 위치 로딩된 조각)을 그대로 둘 수 있을까?

**관련 자료 리서치 중**

* https://stackoverflow.com/questions/29203312/how-can-i-retain-the-scroll-position-of-a-scrollable-area-when-pressing-back-but

**Comment by hynchl** [comment]
document.cookie를 활용하는 방법도 있을 것 같습니다!
https://ko.javascript.info/cookie
